### PR TITLE
[FIX] Add esbuild plugin to generate ts decorator metadata

### PR DESCRIPTION
**Pull request by Romakita**
- Updated tsconfig to avoid embedded **cjs** and **esm** code of tsed (added `"module": "EsNext"` option on tsconfig)
- Added `esbuild-plugin-tsc` + `./esbuild.plugins.cjs` to generate typescript metadata correctly. Metadata is required by decorators and typescript framework to now if a props/params is String/Number or something else. Without these metadata, the framework will considers props/params as an **Object** type.
- Added `import "@tsed/ajv"` in handler.ts to enable ValidationPipe and AJV schema validation.

> Note: The project works as expected on MacOs M1 (all arch)
> Have you node.js 20 installed ? have you run `yarn install` ?

### CODE REVIEW

**Comment by Romakita** [comment]
Capture d’écran 2024-03-25 à 09 03 52

**Comment by ygyg70** [comment]
Node version is v20.11.1
I also deleted yarn.lock and all node_modules files and run ```yarn install``` again, with the same results
Deleted the project and checked out again - same
It is probably something local to my system - don't worry about it. I am not blocked

**Comment by ygyg70** [comment]
Validation now works 👍
File size is now 1023 KB, up from 272 KB, +ajv -minification

**Comment by ygyg70** [comment]
Seems that the distribution size for the full stack (Ts.ED + Express) is around 4.5MB (using ncc)
NestJS has a similar distribution size.

As far as I can tell, NestJS standalone is extremely limited, to the level of not being interesting here.

Question - without minification - does ESBuild has a benefit here over other packaging tools?

**Comment by Romakita** [comment]
@ygyg70 In our example, esbuild is managed by the `sls` command. It's a plus for a the DX. (the alternative is serverless-wepback)

Esbuild is really fast rather than webpack bundler. It use latest ESM code convention ^^.


> Seems that the distribution size for the full stack (Ts.ED + Express) is around 4.5MB (using ncc)
NestJS has a similar distribution size.

You can play with the esbuild option to externalize some dependencies: https://www.serverless.com/plugins/serverless-esbuild 
Serverless provide a bundler analyzer tools: https://github.com/adriencaccia/serverless-analyze-bundle-plugin

I'm open to optimize the frameworks if it's needed (and possible) ^^

**Comment by ygyg70** [comment]
Currently Lambdas are deployed using either Terraform or SAM - Serverless will be another new component - trying to keep things as simple as possible..
I am also hoping that bundle size of 5-10 MB will be acceptable if it enables keeping everything else simple.
most important is to improve developer productivity and product quality without getting into a long tooling project, while keeping options for optimization down the road.

**Comment by Romakita** [comment]
Yes I see. The stack is compatible with a pure Terraform / SAM /AWS approach. Serverless is just a + and it can be replaced by another things. While the handler code is correct and correctly bundled, it's fine.

I haven't example using terraform/SAM but there are many example base on Express.js and should be not a huge rework to have the same things with the actual repository example.

Personnaly, I use the serverless framework to emulate the lambda on local. But alternative tools can be used!

**Pull request merged**
